"""some changes

Revision ID: 0cac60839c6c
Revises: 6e45e7c5ec88
Create Date: 2025-03-18 20:38:14.169450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cac60839c6c'
down_revision: Union[str, None] = '6e45e7c5ec88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutra_click', sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('teaser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('click_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('oneprofit_click', 'source_site_id')
    op.drop_column('oneprofit_click', 'source_teaser_id')
    op.drop_column('oneprofit_click', 'source_click_id')
    op.drop_column('oneprofit_click', 'source_campaign_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oneprofit_click', sa.Column('source_campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_click_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_teaser_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_site_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('oneprofit_click', 'campaign_id')
    op.drop_column('oneprofit_click', 'click_id')
    op.drop_column('oneprofit_click', 'teaser_id')
    op.drop_column('oneprofit_click', 'site_id')
    op.drop_column('nutra_click', 'source_name')
    # ### end Alembic commands ###
