"""add country_code and city to sqlmodel models

Revision ID: 0d1404cb2bb9
Revises: a4d104d4072c
Create Date: 2025-03-18 21:21:46.741584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d1404cb2bb9'
down_revision: Union[str, None] = 'a4d104d4072c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutra_click', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oneprofit_click', 'city')
    op.drop_column('oneprofit_click', 'country_code')
    op.drop_column('nutra_click', 'city')
    op.drop_column('nutra_click', 'country_code')
    # ### end Alembic commands ###
