"""Initial migration

Revision ID: 30a5e3738696
Revises: 
Create Date: 2025-03-18 21:54:27.994312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30a5e3738696'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutra_click', sa.Column('offer_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('landing_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('nutra_click', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutra_click', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('nutra_click', 'landing_name')
    op.drop_column('nutra_click', 'offer_category')
    # ### end Alembic commands ###
