"""add some extra parameters to sqlmodel models

Revision ID: 378ee9334d2f
Revises: 539c459eab1c
Create Date: 2025-03-19 18:19:36.572355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '378ee9334d2f'
down_revision: Union[str, None] = '539c459eab1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutra_click', sa.Column('source_block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('source_device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('source_browser', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('source_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('source_platform_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('source_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('subid1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('subid2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('subid3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('subid4', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('subid5', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('nutra_click', 'block_id')
    op.drop_column('nutra_click', 'device_type')
    op.add_column('oneprofit_click', sa.Column('source_block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_browser', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_platform_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('source_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('subid1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('subid2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('subid3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('subid4', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('subid5', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('oneprofit_click', 'block_id')
    op.drop_column('oneprofit_click', 'device_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oneprofit_click', sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('oneprofit_click', sa.Column('block_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('oneprofit_click', 'subid5')
    op.drop_column('oneprofit_click', 'subid4')
    op.drop_column('oneprofit_click', 'subid3')
    op.drop_column('oneprofit_click', 'subid2')
    op.drop_column('oneprofit_click', 'subid1')
    op.drop_column('oneprofit_click', 'source_city')
    op.drop_column('oneprofit_click', 'source_platform_version')
    op.drop_column('oneprofit_click', 'source_platform')
    op.drop_column('oneprofit_click', 'source_language')
    op.drop_column('oneprofit_click', 'source_browser')
    op.drop_column('oneprofit_click', 'source_device_type')
    op.drop_column('oneprofit_click', 'source_block_id')
    op.add_column('nutra_click', sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nutra_click', sa.Column('block_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('nutra_click', 'subid5')
    op.drop_column('nutra_click', 'subid4')
    op.drop_column('nutra_click', 'subid3')
    op.drop_column('nutra_click', 'subid2')
    op.drop_column('nutra_click', 'subid1')
    op.drop_column('nutra_click', 'source_city')
    op.drop_column('nutra_click', 'source_platform_version')
    op.drop_column('nutra_click', 'source_platform')
    op.drop_column('nutra_click', 'source_language')
    op.drop_column('nutra_click', 'source_browser')
    op.drop_column('nutra_click', 'source_device_type')
    op.drop_column('nutra_click', 'source_block_id')
    # ### end Alembic commands ###
