"""allow none values in oneprofit click table

Revision ID: 51c1c14fe88c
Revises: 73f684cc52da
Create Date: 2025-03-18 20:04:42.170896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51c1c14fe88c'
down_revision: Union[str, None] = '73f684cc52da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oneprofit_click', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('oneprofit_click', 'user_ip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('oneprofit_click', 'news_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('oneprofit_click', 'flow_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oneprofit_click', 'flow_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oneprofit_click', 'news_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oneprofit_click', 'user_ip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oneprofit_click', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
