"""add user agent parser

Revision ID: 539c459eab1c
Revises: 
Create Date: 2025-03-19 18:12:19.332595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '539c459eab1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutra_click', sa.Column('user_agent_browser', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('user_agent_browser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('user_agent_os', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('user_agent_os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('user_agent_device', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('user_agent_browser', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('user_agent_browser_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('user_agent_os', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('user_agent_os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('user_agent_device', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oneprofit_click', 'user_agent_device')
    op.drop_column('oneprofit_click', 'user_agent_os_version')
    op.drop_column('oneprofit_click', 'user_agent_os')
    op.drop_column('oneprofit_click', 'user_agent_browser_version')
    op.drop_column('oneprofit_click', 'user_agent_browser')
    op.drop_column('nutra_click', 'user_agent_device')
    op.drop_column('nutra_click', 'user_agent_os_version')
    op.drop_column('nutra_click', 'user_agent_os')
    op.drop_column('nutra_click', 'user_agent_browser_version')
    op.drop_column('nutra_click', 'user_agent_browser')
    # ### end Alembic commands ###
