"""add block_id and device_type to all models(nutra/vitrina)

Revision ID: a4d104d4072c
Revises: 0cac60839c6c
Create Date: 2025-03-18 21:01:08.333456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4d104d4072c'
down_revision: Union[str, None] = '0cac60839c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutra_click', sa.Column('source_cpc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('nutra_click', sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('oneprofit_click', sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oneprofit_click', 'device_type')
    op.drop_column('oneprofit_click', 'block_id')
    op.drop_column('nutra_click', 'device_type')
    op.drop_column('nutra_click', 'block_id')
    op.drop_column('nutra_click', 'source_cpc')
    # ### end Alembic commands ###
